apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webrtc-sip-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/<project-id>/webrtc-sip-api:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: webrtc-sip-api-secrets
                  key: api-key
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: webrtc-sip-api-secrets
                  key: api-secret
            - name: SIP_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: webrtc-sip-api-secrets
                  key: sip-domain
            - name: SIP_WSS_URL
              valueFrom:
                secretKeyRef:
                  name: webrtc-sip-api-secrets
                  key: sip-wss-url
          startupProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Secret
metadata:
  name: webrtc-sip-api-secrets
type: Opaque
data:
  api-key: <base64-encoded-api-key>
  api-secret: <base64-encoded-api-secret>
  sip-domain: <base64-encoded-sip-domain>
  sip-wss-url: <base64-encoded-sip-wss-url>